### ISSUE TITLE
Change to structured logging!

### ISSUE THREAD

**Issue by sallyom** [containers/fetchit#126]
After we complete https://github.com/redhat-et/harpoon/issues/119 that involves initial error cleanup, we can go thru and switch all to structured logging, which (I) should have done from the get-go. 

Infof -> InfoS
Errorf -> ErrorS

/assign

**Comment by sallyom** [comment]
getting back to this - I think we should update to zap https://github.com/uber-go/zap
it will provide structured logging or unstructured depending on what is needed/where, has leveled logging, and nice output.
 The Zap/Lumberjack logger example in this blog is nice: https://programmer.ink/think/using-zap-log-library-in-go-language-project.html

**Comment by cooktheryan** [comment]
it looks like we are officially done with klog
