### ISSUE TITLE
Support adding capabilities

### ISSUE THREAD

**Issue by tmds** [containers/fetchit#178]
Make it possible to specify Linux additional capabilities to be added to the container.

cc @cooktheryan

**Comment by cooktheryan** [comment]
👍

**Comment by tmds** [comment]
Thanks!
When should this become part of `quay.io/fetchit/fetchit`?

**Comment by cooktheryan** [comment]
This should be available now. One of the CI tasks stopped the image push

**Comment by cooktheryan** [comment]
@tmds fixed!
