### ISSUE TITLE
How to test locally

### ISSUE THREAD

**Issue by andrei-n-cosma** [containers/fetchit#270]
As I couldn't find anything in documentation about it, I want to know how you develop/test locally without referencing a remote git repository.
Currently I'm mounting the manifest-repo at /opt/manifest-repo and a clone of it (/opt/repo) having the remote file:///opt/manifest-repo but that seems awkward. Do you have other way of developing without pushing changes to remote repo?
Thanks.

**Comment by cooktheryan** [comment]
@andrei-n-cosma let me know if the latest push helps out. I wonder if you could modify the volume mount or copy your manifest-repo into the podman volume manually

**Comment by andrei-n-cosma** [comment]
@cooktheryan Thanks. I might have not explained quite well what's the issue I'm having - I want to be able to modify the fetchit configuration without having to rely on a remote git repository.
```
targetConfigs:
- url: http://github.com/containers/fetchit
```
This points to a repository which has to exists and to have the files required to do some deployment (kube play). So that means that I already pushed the configuration to the target repository. I would like to be able to write the configuration and test it locally (before pushing it to remote repo).
It might be that this case is covered by
```
targetConfigs:
- disconnected: true
  device: /dev/sda1
```
but I can't get it working without too many changes, because my partition is encrypted so I'll have to add cryptsetup in the image and extra changes. So I'm curious how you test some configuration (kube play) before pushing it to repository to became an example.

**Comment by cooktheryan** [comment]
so for this scenario and testing I was doing I was using a USB drive. 

https://youtu.be/F3or1YV6HgA
